[package]
name = "Raycasting_diorama"
version = "0.1.0"
edition = "2021"

[dependencies]
image = "0.25.2"
minifb = "0.27.0"
nalgebra-glm = "0.19.0"
pixels = "0.14.0"
rayon = "1.10.0"
winit = "0.30.5"
